server:
  port: 9002

roses:
  log:
    kafka: false
    trace: false
    level: error,info

spring:
  application:
    name: roses-checker
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_message?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        watch-delay: 1000
        server-addr: 127.0.0.1:8848
    # sentinel控制台
    sentinel:
      transport:
        #控制台的ip
        dashboard: localhost:8080
        #指定和控制台通信的ip
        client-ip: 127.0.0.1
        #指定和控制台通信的端口，默认8719
        port: 8719
        #和控制台通信的心跳，默认10秒
        heartbeat-interval-ms: 10000

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.roses.message.api.model
  mapper-locations:
    - classpath*:cn/stylefeng/**/mapping/*.xml

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-message-service

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
